import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { auth, clerkClient } from "@clerk/nextjs/server";
import Sidebar from "@/components/dasboard/sidebar";
import Header from "@/components/dasboard/header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const {userId} = await auth()
    const client = await clerkClient()
    const user = (await client.users.getUser(userId))
    const role = user.publicMetadata.role

    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <div className="flex">
                        <Sidebar role={role}/>
                        <div className="grow p-3 w-3xl md:w-4xl lg:w-5xl xl:w-6xl overflow-x-hidden">
                            <Header />
                            {children}
                            <Toaster richColors={true}/>
                        </div>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
