import Header from "@/components/header";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { cookies } from "next/headers";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
            <html>
                <body>
                    <Header />
                    {children}
                </body>
            </html>
    );
}
