import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {JetBrains_Mono, Noto_Kufi_Arabic} from "next/font/google"
import {NextIntlClientProvider} from 'next-intl';
import { cookies } from "next/headers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const jetBrains = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-jetbrains"
})

export const kufi = Noto_Kufi_Arabic({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-kufi"
})


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookie = await cookies()

  const lang = cookie.get("locale")?.value || "en"
  

  return (
      <ClerkProvider>
        <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"} className={`${lang === "ar" ? kufi.variable : jetBrains.variable}`}>
          <body>
            <NextIntlClientProvider>
              {children}
            </NextIntlClientProvider>
          </body>
        </html>
      </ClerkProvider>
  );
}
