import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ImageKitProvider } from '@imagekit/next';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const urlEndPoint = process.env.NEXT_PUBLIC_URL_ENDPOINT

  return (
    <ImageKitProvider urlEndpoint={urlEndPoint}>
      <ClerkProvider>
        <html lang="en">
          <body>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </ImageKitProvider>
  );
}
